finance/urls.py
from django.urls import path
from . import views

app_name = 'finance'


urlpatterns = [
    path('', views.home_view, name='home'),
    path('create_financial_change', views.FinancialChangeCreateView.as_view(), name='create_financial_change'),
    path('detail_financial_change/<int:pk>', views.FinancialChangeDetailView.as_view(), name='detail_financial_change'),
    path('list_financial_change', views.FinancialChangeListView.as_view(), name='list_financial_change'),
    path('delete_financial_change/<int:pk>', views.FinancialChangeDeleteView.as_view(), name='delete_financial_change'),
    path('update_financial_change/<int:pk>', views.FinancialChangeUpdateView.as_view(), name='update_financial_change'),
    path('summary_chart_data', views.summary_chart_data, name='summary_chart_data'),
    path('income_expenses_chart_data', views.income_expenses_chart_data, name='income_expenses_chart_data'),
    path('financial_change_monthly_sum_by_category', views.financial_change_monthly_sum_by_category,
         name='financial_change_monthly_sum_by_category'),
    path('financial_change_monthly_sum_by_asset_type', views.financial_change_monthly_sum_by_asset_type,
         name='financial_change_monthly_sum_by_asset_type'),
    path('sum_by_asset_type', views.sum_by_asset_type, name='sum_by_asset_type'),
    path('import_transfer_file', views.import_transfer_file_form, name='import_transfer_file'),
    path('financial_change_from_transfer_create', views.create_financial_change_from_transfer_form,
         name='financial_change_from_transfer')

]

homeApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('finance/', include('finance.urls')),
    path('', views.home_view, name='home')
]

templates/base.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

    <title>House Management</title>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}"><i class="bi bi-house-door"></i></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'finance:home' %}"> <i class="bi bi-piggy-bank"></i> Finance</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% block content %}


{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col">
                <a class="btn btn-outline-primary" role="button" aria-disabled="true" href="{% url 'finance:home' %}">Finance</a>
                
            </div>
            <div class="col">

            </div>
        </div>
    </div>

{% endblock %}