finance/urls.py
from django.urls import path
from . import views

app_name = 'finance'


urlpatterns = [
    path('', views.home_view, name='home'),
    path('create_financial_change', views.FinancialChangeCreateView.as_view(), name='create_financial_change'),
    path('detail_financial_change/<int:pk>', views.FinancialChangeDetailView.as_view(), name='detail_financial_change'),
    path('list_financial_change', views.FinancialChangeListView.as_view(), name='list_financial_change'),
    path('delete_financial_change/<int:pk>', views.FinancialChangeDeleteView.as_view(), name='delete_financial_change'),
    path('update_financial_change/<int:pk>', views.FinancialChangeUpdateView.as_view(), name='update_financial_change'),
    path('summary_chart_data', views.summary_chart_data, name='summary_chart_data'),
    path('income_expenses_chart_data', views.income_expenses_chart_data, name='income_expenses_chart_data'),
    path('financial_change_monthly_sum_by_category', views.financial_change_monthly_sum_by_category,
         name='financial_change_monthly_sum_by_category'),
    path('financial_change_monthly_sum_by_asset_type', views.financial_change_monthly_sum_by_asset_type,
         name='financial_change_monthly_sum_by_asset_type'),
    path('sum_by_asset_type', views.sum_by_asset_type, name='sum_by_asset_type'),
    path('import_transfer_file', views.import_transfer_file_form, name='import_transfer_file'),
    path('financial_change_from_transfer_create', views.create_financial_change_from_transfer_form,
         name='financial_change_from_transfer')

]

homeApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('finance/', include('finance.urls')),
    path('', views.home_view, name='home')
]

finance/models.py
from django.db import models


class Account(models.Model):
    OWNERS = (
        ('A', 'Adrian'),
        ('J', 'Asia')
    )
    name = models.CharField(max_length=255)
    number = models.CharField(max_length=255)
    owner = models.CharField(max_length=1, choices=OWNERS)

    def __str__(self):
        return f'{self.get_owner_name()} {self.name}'

    def get_owner_name(self):
        for o in self.OWNERS:
            if o[0] == self.owner:
                return o[1]
        return 'Error'


class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.name}'


class AssetType(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.name}'


class FinancialChange(models.Model):
    DIRECTIONS = (
        ('I', 'Incoming'),
        ('O', 'Outgoing')
    )
    name = models.CharField(max_length=255)
    amount_gr = models.DecimalField(max_digits=20, decimal_places=2)
    date = models.DateField(null=True)
    direction = models.CharField(max_length=1, choices=DIRECTIONS)
    account = models.ForeignKey(Account, null=True, on_delete=models.SET_NULL)
    asset_type = models.ForeignKey(AssetType, null=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'financial change name {self.name} amount {self.amount_gr}'


class Reduction(models.Model):
    REDUCTION_TYPES = (
        ('B', 'Between Accounts'),
        ('R', 'Loan Return'),
        ('K', 'Brokerage')
    )

    type = models.CharField(max_length=1, choices=REDUCTION_TYPES)
    reductor = models.ForeignKey(FinancialChange, on_delete=models.CASCADE, related_name='reductor')
    reduced = models.ForeignKey(FinancialChange, on_delete=models.CASCADE, related_name='reduced')


class Transfer(models.Model):
    DIRECTIONS = (
        ('I', 'Incoming'),
        ('O', 'Outgoing')
    )
    STATUSES = (
        ('I', 'Inserted'),
        ('P', 'Postponed'),
        ('T', 'To insert')
    )
    sender_receiver = models.CharField(max_length=255, null=True)
    title = models.CharField(max_length=255, null=True)
    outer_account = models.CharField(max_length=30, null=True)
    operation_date = models.DateField(null=True)
    posting_date = models.DateField(null=True)
    description = models.CharField(max_length=255, null=True)
    amount_gr = models.DecimalField(max_digits=20, decimal_places=2)
    direction = models.CharField(max_length=1, choices=DIRECTIONS)
    status = models.CharField(max_length=1, choices=STATUSES, null=True)
    balance = models.DecimalField(max_digits=20, decimal_places=2)
    inner_account = models.ForeignKey(Account, null=True, on_delete=models.SET_NULL)
    financial_change = models.ForeignKey(FinancialChange, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        if self.direction == 'I':
            return f"incoming from {self.sender_receiver} amount {self.amount_gr} zl"
        else:
            return f"outgoing to {self.sender_receiver}  amount {self.amount_gr} zl"

finance/forms.py
from django import forms
from django.forms import DateInput

from . import models


class ImportTransfersForm(forms.Form):
    import_file = forms.FileField()


def get_category_choices():
    categorys = models.Category.objects.all()
    category_choices = []
    for cat in categorys:
        new_choice = (cat.name.__str__(), cat.name.__str__())
        category_choices.append(new_choice)
    return category_choices


def get_status_choices():
    status_choices = []
    statuses = models.Transfer.STATUSES


class FinancialChangeForm(forms.Form):
    name = forms.CharField()
    category = forms.ChoiceField(choices=get_category_choices())
    status = forms.ChoiceField(choices=models.Transfer.STATUSES, widget=forms.RadioSelect)










"""  date = forms.DateField(widget=forms.DateInput())"""

"""    date = forms.DateField(null=True)
    direction = forms.ChoiceField(max_length=1, choices=DIRECTIONS)
"""

"""   account = forms.ChoiceField(choices=models.Account.all())
   asset_type = forms.ForeignKey(AssetType, null=True, on_delete=models.SET_NULL)
   category = forms.ForeignKey(Category, null=True, on_delete=models.SET_NULL)
"""

"""  DIRECTIONS = (
      ('I', 'Incoming'),
      ('O', 'Outgoing')
  )
  name = models.CharField(max_length=255)
  amount_gr = models.DecimalField(max_digits=20, decimal_places=2)
  date = models.DateField(null=True)
  direction = models.CharField(max_length=1, choices=DIRECTIONS)
  account = models.ForeignKey(Account, null=True, on_delete=models.SET_NULL)
  asset_type = models.ForeignKey(AssetType, null=True, on_delete=models.SET_NULL)
  category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)
"""

finance/views.py
import csv
import io

from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from .forms import FinancialChangeForm, ImportTransfersForm
from finance.models import FinancialChange
# Create your views here.
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from finance.utils.financial_dashboard import get_wealth_sum, get_current_cash
from django import forms
from finance.utils.csv_transfer_import import import_csv_transfers
from finance.utils.financial_change_from_transfer.LatestTransformPresentationStringProvider import LatestTransformPresentationStringProvider

from .utils.charts import get_summary_chart_data, get_income_expenses_chart_data, \
    get_financial_change_monthly_sum_by_category, get_financial_change_by_asset_type, get_asset_sums
from .utils.financial_change_from_transfer.FinancialChangeFromTransferCreator import FinancialChangeFromTransferCreator

def home_view(request):
    context = {
        'wealth_sum': get_wealth_sum('Adrian'),
        'cash_sum': get_current_cash()
    }
    return render(request, 'finance/index.html', context=context)


class FinancialChangeCreateView(CreateView):
    model = FinancialChange
    fields = "__all__"
    success_url = reverse_lazy('finance:list_financial_change')
    widgets = {
        'date': forms.SelectDateWidget()
    }


def import_transfer_file_form(request):
    if request.method == 'POST':
        form = ImportTransfersForm(request.POST, request.FILES)
        if form.is_valid():
            import_csv_transfers(request.FILES)
            return redirect(reverse('finance:financial_change_from_transfer'))
    else:
        form = ImportTransfersForm()
    return render(request, 'finance/import_transfer_file.html', context={'form': form})


def create_financial_change_from_transfer_form(request):
    if request.method == 'POST':
        form = FinancialChangeForm(request.POST)
        if form.is_valid():
            fc_creator = FinancialChangeFromTransferCreator(request.POST)
            fc_creator.set_transfer_status()
            if(request.POST['status'] == 'I'):
                fc_creator.insert_new_financial_change()
            return redirect(reverse('finance:financial_change_from_transfer'))
    else:
        form = FinancialChangeForm()
        transfer_pres = LatestTransformPresentationStringProvider()
    return render(request, 'finance/financial_change_from_transfer_create.html', context={'form': form, 'transfer': transfer_pres})


class FinancialChangeListView(ListView):
    model = FinancialChange
    # Peform any .filter() you want here to only list certain items
    # queryset = Teacher.objects.order_by('first_name')
    # customize the name of the object_list sent to template
    context_object_name = 'object_list'


class FinancialChangeUpdateView(UpdateView):
    model = FinancialChange
    fields = '__all__'
    success_url = reverse_lazy('finance:list_financial_change')


class FinancialChangeDeleteView(DeleteView):
    model = FinancialChange
    success_url = reverse_lazy('finance:list_financial_change')


class FinancialChangeDetailView(DetailView):
    model = FinancialChange


def summary_chart_data(request):
    return JsonResponse(get_summary_chart_data())


def income_expenses_chart_data(request):
    return JsonResponse(get_income_expenses_chart_data())


def financial_change_monthly_sum_by_category(request):
    return JsonResponse(get_financial_change_monthly_sum_by_category())


def financial_change_monthly_sum_by_asset_type(request):
    return JsonResponse(get_financial_change_by_asset_type())


def sum_by_asset_type(request):
    return JsonResponse(get_asset_sums())

finance/templates/finance/financial_change_create.html
{% extends 'base.html' %}

{% block content %}


    <h1> New financial change </h1>
    <form action="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
    </form>

{% endblock %}

finance/templates/finance/financial_change_from_transfer_create.html
{% extends 'base.html' %}

{% block content %}


    <h1> New financial change from transfer</h1>
    <div class="container">
        <div class="row">
            <div class="col">
                <h2 style="color:{{ transfer.direction_colour }};">Przelew {{ transfer.direction }}</h2>
            </div>
            <div class="col">
                <h2 style="color:{{ transfer.direction_colour }};">{{ transfer.transfer.amount_gr }} zł</h2>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <h3>od: {{ transfer.from_s }}</h3>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <h3>do: {{ transfer.to }}</h3>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <h3>tytuł: {{ transfer.transfer.title }}</h3>
            </div>
        </div>
        <div class="row">
            <div class="col">
                data przelewu: {{ transfer.transfer.operation_date }}
            </div>
            <div class="col">
                data księgowania: {{ transfer.transfer.posting_date }}
            </div>
            <div class="col">
                saldo: {{ transfer.transfer.balance }}
            </div>
            <div class="col">
                opis: {{ transfer.transfer.description }}
            </div>
        </div>
    </div>
    <br>
    <br>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type='hidden' name="transfer_pk" value="{{ transfer.transfer.pk }}" />
        <input type="submit" value="Submit">
    </form>

{% endblock %}

finance/templates/finance/financialchange_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <h1>Are you sure do you want to delete this entry?</h1>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm DELETE">
</form>
{% endblock %}

finance/templates/finance/financialchange_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1> delete </h1>


{% endblock %}

finance/templates/finance/financialchange_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1> financial change detail </h1>
    {{ financialchange.name }}

{% endblock %}

finance/templates/finance/financialchange_form.html
{% extends 'base.html' %}

{% block content %}


    <h1> New financial change </h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Submit">
    </form>

{% endblock %}

finance/templates/finance/financialchange_list.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col">
                <a class="btn btn-outline-primary" role="button" aria-disabled="true"
                   href="{% url 'finance:create_financial_change' %}">Add change</a>
            </div>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Name</th>
            <th scope="col">Amount</th>
            <th scope="col">Date</th>
            <th scope="col">Direction</th>
            <th scope="col">Account</th>
            <th scope="col">Asset type</th>
            <th scope="col">Category</th>
            <th scope="col">Menu</th>
        </tr>
        </thead>
        <tbody>
        {% for financial_change in object_list %}
            <tr>
                <td>
                    {{ financial_change.pk }}
                </td>
                <td>
                    {{ financial_change.name }}
                </td>
                <td>
                    {{ financial_change.amount_gr}}
                </td>
                <td>
                    {{ financial_change.date }}
                </td>
                <td>
                    {{ financial_change.direction }}
                </td>
                <td>
                    {{ financial_change.account }}
                </td>
                <td>
                    {{ financial_change.asset_type }}
                </td>
                <td>
                    {{ financial_change.category }}
                </td>
                <td>
                    <a class="navbar-brand" href="/finance/update_financial_change/{{ financial_change.pk }}"><i class="bi bi-pencil"></i></a>
                    <a class="navbar-brand" href="/finance/delete_financial_change/{{ financial_change.pk }}"><i class="bi bi-trash3"></i></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

finance/templates/finance/import_transfer_file.html
{% extends 'base.html' %}

{% block content %}
<h1> Import file transfer </h1>
    <br>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}